### ISSUE TITLE
`xtensor-r` will need more types defined in `xcontainer_inner_types`

### ISSUE THREAD

**Issue by DavisVaughan** [QuantStack/xtensor-r#100]
Don't have quite enough time today to submit a PR for this, but I was trying to install master branches of everything and with the master branch of xtensor, we now need:

```
using reference = typename storage_type::reference;
using const_reference = typename storage_type::const_reference;
using size_type = typename storage_type::size_type;
```

all defined in both `xcontainer_inner_types<rtensor<T, N>>` and `xcontainer_inner_types<rarray<T>>`

**Comment by JohanMabille** [comment]
Indeed the incoming release of `xtensor` is a backward incompatible release that need some work in the bindings projects.

**Comment by SylvainCorlay** [comment]
also, we can totally add these typedefs in `xtensor-r` and `xtensor-julia` before the release of xtensor. We have already done it for `xtensor-python`. Adding these typedefs is a backward-compatible change.

Feel free to open a PR is you want to move to the master branches.

**Comment by SylvainCorlay** [comment]
This is fixed in master.
