### ISSUE TITLE
R CMD build is run in wrong directory

### ISSUE THREAD

**Issue by wolfv** [QuantStack/xtensor-r#12]
When executing `bash r-packaging.sh` the resulting xtensor... tar.xz doesn't contain the headers. This is, because the folder in which `R CMD build R-package` is executed in is the root folder and not `build`, so only the template get's packaged.

**Comment by SylvainCorlay** [comment]
Right it must be run from the build folder.

**Comment by SylvainCorlay** [comment]
I fixed the readme.
