### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by alexpghayes** [QuantStack/xtensor-r#25]
Very newbie question: I'd love to use xtensor-r before the CRAN release (can't wait to have the Numpy API in Rcpp!). But

```
conda install -c conda-forge xtensor-r
```

gives a package not found error. Googling I wasn't able to find a conda-forge xtensor-r package. Building from source is similarly a bit over my head.

Is there a way to `devtools::install_github` in the meantime? I gave 

```r
devtools::install_github("QuantStack/xtensor-r/tree/master/R-package")
```
a go but no luck.

**Comment by SylvainCorlay** [comment]
Hi @alexpghayes , unfortunately, we have not pushed the conda or cran packages yet, so if you want to be on the bleeding edge, the only way is to install it from source.

For example

```
mkdir build
cd build
cmake ..
make cran
```

will generate the cran tarball that you can install with R classically.

We will not support the `install_github` features which requires the GitHub repository to basically contain the content of the cran package, which would mean a lot of generated content and the vendoring of xtensor core. The `cran` cmake generates something that you can use.

**Comment by SylvainCorlay** [comment]
Note, I have just edited the instruction after noticing that you are on windows

**Comment by alexpghayes** [comment]
Thanks for the quick response!

After adding `C:\RBuildTools\3.4\mingw_64\bin;C:\Program Files\R\R-3.4.1\bin` to my PATH, I can generate `xtensor_0.1.0-0.tar.gz`. Now when I run

```r
install.packages('xtensor_0.1.0-0.tar.gz')
```

I get:

```
Error in .shlib_internal(args) :
  C++14 standard requested but CXX14 is not defined
```

**Comment by wolfv** [comment]
It sounds like something akin to this: https://github.com/Microsoft/microsoft-r-open/issues/26#issuecomment-313739668

has to be done in this file here: https://github.com/QuantStack/xtensor-r/blob/master/R-package/src/Makevars.win

E.g. setting

```
CXX14 = g++
CXX14FLAGS = -O2 -g $(LTO)
CXX14PICFLAGS = -fPIC
CXX14STD = -std=c++14

SHLIB_CXX14LD = $(CXX14) $(CXX14STD)
SHLIB_CXX14LDFLAGS = -shared
```

But this is just an idea and might not work ...

**Comment by SylvainCorlay** [comment]
@alexpghayes can you try with the latest changes in master?

**Comment by alexpghayes** [comment]
Sorry for the delay. Getting the exact same issue as before (didn't make any changes to most recent `Makevars.win`).

```r
> install.packages('xtensor_0.1.0-0.tar.gz')
Installing package into 'C:/Users/alex/Documents/R/win-library/3.4'
(as 'lib' is unspecified)
inferring 'repos = NULL' from 'pkgs'
* installing *source* package 'xtensor' ...
** libs

*** arch - i386
Error in .shlib_internal(args) :
  C++14 standard requested but CXX14 is not defined
* removing 'C:/Users/alex/Documents/R/win-library/3.4/xtensor'
Warning messages:
1: running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" CMD INSTALL -l "C:\Us
alex\Documents\R\win-library\3.4" "xtensor_0.1.0-0.tar.gz"' had status 1
2: In install.packages("xtensor_0.1.0-0.tar.gz") :
  installation of package 'xtensor_0.1.0-0.tar.gz' had non-zero exit status
```

**Comment by SylvainCorlay** [comment]
@alexpghayes just removing CXX14 from Makevar.win should do it. 

The way R handles this is really an issue. The current version on master does not have that flag anymore.

**Comment by SylvainCorlay** [comment]
@alexpghayes I am closing this issue since this seems to work ok when removing CXX14 from the Makevar file (which is now done on master). We are now in the submission process to CRAN.

**Comment by SylvainCorlay** [comment]
@alexpghayes the package is on CRAN!

**Comment by alexpghayes** [comment]
Look forward to giving it a go! Sorry haven't been responsive -- classes just hit full ahead.

Thanks for making this happen!
