### ISSUE TITLE
Assign rtensor in parallel

### ISSUE THREAD

**Issue by artemklevtsov** [QuantStack/xtensor-r#58]
I tried to fill `rtensor` with TBB. My code crashed with the following message:

> terminated by signal SIGSEGV (Address boundary error)

Below code to reproduce:

```cpp
// [[Rcpp::depends(xtensor)]]
// [[Rcpp::depends(RcppParallel)]]
// [[Rcpp::plugins(cpp14)]]

#include <xtensor/xrandom.hpp>
#include <xtensor/xadapt.hpp>
#include <xtensor/xview.hpp>
#include <xtensor-r/rtensor.hpp>
#include <RcppParallel.h>

const static int SIZE = 256;
const static int CH = 3;

xt::rtensor<double,3> gen_array() {
    xt::rtensor<double,3> res = xt::random::rand<double>({SIZE, SIZE, CH}, 0, 1);
    return res;
}

// [[Rcpp::export]]
xt::rtensor<double,4> test_xt(int n) {
    xt::rtensor<double,4> res({n, SIZE, SIZE, 3});
    tbb::parallel_for(0, n, [&res](size_t i) {
        xt::rtensor<double,3> tmp = gen_array();
        auto view = xt::view(res, i, xt::all(), xt::all(), xt::all());
        view = tmp;
    });
    return res;
}

/***R
dim(test_xt(1000))
*/
```

Command to debug:

```bash
env LANG=C R -d "valgrind --tool=helgrind --log-file=out.log" -e 'Rcpp::sourceCpp("test_xt.cpp")'
```

`helgrind` log is attached.
[out.log](https://github.com/QuantStack/xtensor-r/files/2568385/out.log)

**Comment by wolfv** [comment]
hi @artemklevtsov 

could you use a xtensor instead of an rtensor for the array with random values? That way we can eliminate one source of error for the moment.

E.g.:

```cpp
// [[Rcpp::depends(xtensor)]]
// [[Rcpp::depends(RcppParallel)]]
// [[Rcpp::plugins(cpp14)]]

#include <xtensor/xrandom.hpp>
#include <xtensor/xadapt.hpp>
#include <xtensor/xview.hpp>
#include <xtensor-r/rtensor.hpp>
#include <RcppParallel.h>

const static int SIZE = 256;
const static int CH = 3;

xt::xtensor<double,3,xt::layout_type::column_major> gen_array() {
    xt::xtensor<double,3,xt::layout_type::column_major> res = xt::random::rand<double>({SIZE, SIZE, CH}, 0, 1);
    return res;
}

// [[Rcpp::export]]
xt::rtensor<double,4> test_xt(int n) {
    xt::rtensor<double,4> res({n, SIZE, SIZE, 3});
    tbb::parallel_for(0, n, [&res](size_t i) {
        xt::xtensor<double,3,xt::layout_type::column_major> tmp = gen_array();
        auto view = xt::view(res, i, xt::all(), xt::all(), xt::all());
        view = tmp;
    });
    return res;
}
```

If this does not show the same issue, we need to investigate wether we're not safe-guarding the R memory allocation in the correct way for multithreaded programs.

**Comment by artemklevtsov** [comment]
I confirmed the `xt::xtensor` works without errors.

**Comment by wolfv** [comment]
In the RcppParallel docs they mention https://rcppcore.github.io/RcppParallel/#thread_safety
there is some more guidance. 

Note that the *creation* of a rtensor calls into the R API which is not thread safe, quoting the docs:

> Calling any of the R API from threaded code is ‘for experts only’: they will need to read the source code to determine if it is thread-safe. In particular, code which makes use of the stack-checking mechanism must not be called from threaded code.

I think using a xtensor as this internal tensor that's created in the threaded code is the correct solution.
