### ISSUE TITLE
Support R logical vectors

### ISSUE THREAD

**Issue by wolfv** [QuantStack/xtensor-r#62]
R stores booleans as int32.
This means that we would need to add a proxy type to cast to a storage that is an int32 but behaves otherwise like a bool.

**Comment by DavisVaughan** [comment]
Great, I'll take a look this week! Thanks for the head start.

**Comment by DavisVaughan** [comment]
Hi @wolfv and @JohanMabille, I've got some good news. I've got a working implementation over in my `xtensorrr` library (I just keep a copy there with all of the headers for ease of install when using rstudio).

Here is a summary of the changes so far:
https://github.com/DavisVaughan/xtensorrr/compare/support-logical#diff-10c95f056a2334fe2130a5709046caceR27

A few things:

- Currently only supporting rarray but rtensor changes should be pretty similar 
- I can do a full PR for xtensor-r itself if things look good
- you actually already define `get_value_type()`, so I just extended that (did I do it right?) https://github.com/QuantStack/xtensor/blob/3c8dd8b3bcc61d9e27080b7769b3f3bec623d571/include/xtensor/xutils.hpp#L541
- regarding `Rcpp::traits::r_sexptype_traits<T>::rtype` not working, I took the approach of just adding `template<> struct r_sexptype_traits<rlogical>{ enum{ rtype = LGLSXP }; };` to the `Rcpp::traits::` namespace. It seemed to work. [Here](https://github.com/RcppCore/Rcpp/blob/f3c5a34e06e774532227470b01c63a8f08ce4313/inst/include/Rcpp/traits/r_sexptype_traits.h#L38) is where they are all defined for Rcpp.

For that last point, I got the idea from a past post I had seen where dirk extends the wrap() and as() templated functions to work with boost ublas. So I think this is okay? http://gallery.rcpp.org/articles/custom-templated-wrap-and-as-for-seamingless-interfaces/

When I do the full PR, feel free to critique anything so it fits your code style. For now, I'm looking for more of a "am I on the right track?"

Here are a few examples that show it working with `rray`.

``` r
library(rray)

ex <- rray(c(TRUE, FALSE))
ex
#> <vctrs_rray<logical>[,1][2]>
#>      [,1] 
#> [1,]  TRUE
#> [2,] FALSE

# internally converting to rarray<rlogical> and back
rray_broadcast(ex, c(2, 3, 2))
#> <vctrs_rray<logical>[,3,2][12]>
#> , , 1
#> 
#>      [,1]  [,2]  [,3] 
#> [1,]  TRUE  TRUE  TRUE
#> [2,] FALSE FALSE FALSE
#> 
#> , , 2
#> 
#>      [,1]  [,2]  [,3] 
#> [1,]  TRUE  TRUE  TRUE
#> [2,] FALSE FALSE FALSE

as.logical(ex)
#>       [,1]
#> [1,]  TRUE
#> [2,] FALSE

as.integer(ex)
#>      [,1]
#> [1,]    1
#> [2,]    0

# using your elementwise equality
# the return value of equal() gets stored directly
# into rarray<rlogical>
rray_equal(ex, FALSE)
#> <vctrs_rray<logical>[,1][2]>
#>       
#>        [,1] 
#>   [1,] FALSE
#>   [2,]  TRUE

rray_equal(ex, 0)
#> <vctrs_rray<logical>[,1][2]>
#>       
#>        [,1] 
#>   [1,] FALSE
#>   [2,]  TRUE

# example of broadcasting
rray_equal(ex, matrix(c(TRUE, FALSE, TRUE, TRUE), ncol = 2))
#> <vctrs_rray<logical>[,2][4]>
#>       
#>        [,1]  [,2] 
#>   [1,]  TRUE  TRUE
#>   [2,]  TRUE FALSE
```

**Comment by wolfv** [comment]
Hey @DavisVaughan 

Nice! The basic ideas are absolutely correct – and it seems to work, that's cool! 
The changes to `rtensor` will be trivial, just repeat the same stuff as for `rarray`, I agree.

There is one question I have from your example: when you do `rray(c(TRUE, FALSE))` it should print a 1D vector, right? Or does your package handle this differently?

Besides this, here are some comments:

- The `get_value_type` function from xtensor has a slightly different function: it either returns `T`, or if `T` is a type that defines a `value_type` (such as a `std::vector`, or a `xt::xtensor`) it returns that value type (that's what the `void_t` magic is needed for). For the purpose in xtensor-r I would advocate to make a new function.
- Extending the Rcpp traits seems like a good idea. I guess if they've blogged about this we can assume that the interface is stable and is not going to change suddenly! 

I think regarding the value type meta function, how about creating a detail namespace for xtensor-r such as 

```cpp
namespace r_detail
{
    template <class T>
    struct get_underlying_value_type_r
    {
        return T;
    };

    template <>
    struct get_underlying_value_type_r<rlogical>
    {
        return int;
    };
}
```

**Comment by DavisVaughan** [comment]
Thanks!

Regarding 1D vector, my package does handle this differently (everything is at least a 2D matrix with vectors being 1 col matrices) but I'm tempted to revert this behavior.

The r_detail namespace goes in the xt namespace correct?

Otherwise sounds good and I'll make all the changes and PR

**Comment by wolfv** [comment]
I see :) I guess your package is young enough so you can easily make these changes.

yeah, `r_detail` inside the `xt` namespace :+1: 

Cool, looking forward to the PR.
