### ISSUE TITLE
Support R sentinel values

### ISSUE THREAD

**Issue by wolfv** [QuantStack/xtensor-r#63]
All of R's types seem to support NA (and even NaN).

In order to support the `NA` value, we could build a xoptional_assembly with the values being the array, and the optional expression being a xfunction that compares the value array with the sentinel value. 

For Int and Logical the NA value is `INT_MIN`. We need to look into the source to figure out what the NA value is for Real and Complex.

**Comment by DavisVaughan** [comment]
I can give you a full example if you need it, but Real `NA` values seem to actually be working fine. Int definitely don't work, and as you've said in some recent commits (and I've found out the hard way) Logical is not supported at all yet

**Comment by wolfv** [comment]
Hi @DavisVaughan, any chance that you have someone at RStudio who'd like to get deeper into C++ and work on implementing the Logical (or you yourself)?

It's not a lot of work, and we'd be happy to mentor someone through it!

**Comment by DavisVaughan** [comment]
I'd be happy to give it a shot. I've spent a decent amount of time reading through some of the source code, but guidance would definitely be appreciated. I'll be upfront about the fact that C++ isn't my strong suit, but R obviously is and I've generally been able to figure out enough on the C++ side to make things work.

My progress so far has resulted in this 
https://github.com/DavisVaughan/rray

Any pointers on where to get started?

**Comment by wolfv** [comment]
Wow, `rray` looks interesting! I'm curious to see how that plays out.
I replied in the other issue and ping'd you!

**Comment by SylvainCorlay** [comment]
I think that we can close this as we now support R sentinel values!

Working on tagging releases of `xtensor-r` and the R package for `xtensor`.

**Comment by SylvainCorlay** [comment]
Hey @davisvaughan FYI we have released xtensor-r 0.10.0 which includes support for R sentinel values.

It appears that CRAN has trouble with `configure.win` files so this is not on CRAN yet (I posted on rstudio's discourse about this).

`rtensor_optional` and `rarray_optional` wrap r arrays with an xtensor optional semantics (has_value(), value()) and operate on R sentinel values under the hood

**Comment by DavisVaughan** [comment]
I haven't looked too much into it, but what is the expected way for me to use `rarray_optional`? I don't want R users to have to do anything special to use rray's with missing values. Should I just replace all of my uses of `rarray` with `rarray_optional`? Is there a big performance hit if I do this?

**Comment by SylvainCorlay** [comment]
If you expose a function to R with a `rarray_optional` instead of `rarray`, `value()`,

- there is not memory overhead. 
- you basically have the `xoptional` API on elements (with e.g. `value` and `has_value)`. Setting a scalar to an element sets the value and resets the has_value flag to true.
- you also get vectorized `value` and `has_value` methods to the array itself that return expressions which are views on the underlying buffer.

You can assign a value to an optional and it becomes "not missing", or an xexpression of values to an option
